server:
  port: 8080

database:
  host: localhost
  port: 5432
  username: user
  password: password
  database: eventhub
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password:
  db: 0

log:
  mode: debug
  encoding: json
  output_path: ["stdout"]

auth:
  api_key_header: X-API-Key
  access_ttl: 30m
  refresh_ttl: 168h